# Generated by Django 4.0.4 on 2022-05-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0003_alter_message_recipient_alter_message_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel_num',
            field=models.IntegerField(null=True),
        ),
    ]
