# Generated by Django 4.0.4 on 2022-05-28 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0004_alter_profile_tel_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='inne', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(1, 'Przeczytane'), (2, 'Nieprzeczytane'), (3, 'Wersja robocza')]),
        ),
    ]
