# Generated by Django 4.0.4 on 2022-06-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0007_alter_offer_status_alter_offer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Nazwa'),
        ),
    ]
