# Generated by Django 4.0.4 on 2022-06-02 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike_app', '0008_alter_offer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ManyToManyField(to='bike_app.category', verbose_name='Kategoria'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(max_length=1000, verbose_name='Opis'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cena'),
        ),
    ]
